/**
 * Compact, human-typeable cycle sync code.
 *
 * Encodes:
 *   - last period start date (days since 2020-01-01, 14 bits → ~45 years)
 *   - average cycle length, 18..81 days (6 bits)
 *   - average period length, 1..16 days (4 bits)
 *   - CRC16-CCITT checksum (16 bits)
 *
 * Total payload: 24 bits + 16-bit checksum = 40 bits → 8 chars in
 * Crockford base32 (alphabet 0-9 A-Z without I, L, O, U). The visible form
 * groups the chars as `XXXX-XXXX` for readability.
 *
 * The same algorithm is mirrored in `bot/services/cycle_code.py` so the
 * Python side can decode codes generated by the app.
 */

const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const EPOCH_MS = Date.UTC(2020, 0, 1);
const MS_PER_DAY = 24 * 60 * 60 * 1000;

export interface CycleCodePayload {
  /** ISO date `yyyy-MM-dd` of the last confirmed period start. */
  startDate: string;
  /** Average cycle length in days (18..81). */
  cycleLength: number;
  /** Average period length in days (1..16). */
  periodLength: number;
}

const crc16 = (bytes: number[]): number => {
  let crc = 0xffff;
  for (const b of bytes) {
    crc ^= (b & 0xff) << 8;
    for (let i = 0; i < 8; i++) {
      crc = (crc & 0x8000) !== 0 ? ((crc << 1) ^ 0x1021) & 0xffff : (crc << 1) & 0xffff;
    }
  }
  return crc;
};

const daysSinceEpoch = (iso: string): number => {
  const ms = Date.parse(`${iso}T00:00:00Z`);
  if (Number.isNaN(ms)) throw new Error(`Bad date: ${iso}`);
  return Math.floor((ms - EPOCH_MS) / MS_PER_DAY);
};

const epochDayToIso = (days: number): string => {
  const d = new Date(EPOCH_MS + days * MS_PER_DAY);
  return d.toISOString().slice(0, 10);
};

/**
 * Encode a cycle payload into an 8-char base32 string formatted as
 * `XXXX-XXXX`. Throws if any field is out of the supported range.
 */
export const encodeCycleCode = (p: CycleCodePayload): string => {
  const days = daysSinceEpoch(p.startDate);
  if (days < 0 || days >= 1 << 14) {
    throw new Error('Дата вне поддерживаемого диапазона (2020-2064)');
  }
  const c = p.cycleLength - 18;
  if (c < 0 || c >= 1 << 6) {
    throw new Error('Длина цикла вне диапазона 18..81');
  }
  const pl = p.periodLength - 1;
  if (pl < 0 || pl >= 1 << 4) {
    throw new Error('Длина месячных вне диапазона 1..16');
  }
  const payload24 = (days << 10) | (c << 4) | pl;
  const bytes = [
    (payload24 >> 16) & 0xff,
    (payload24 >> 8) & 0xff,
    payload24 & 0xff,
  ];
  const crc = crc16(bytes);
  // 40-bit number — fits in JS double precision (2^40 ≪ 2^53).
  const value = payload24 * 0x10000 + crc;
  let out = '';
  for (let i = 7; i >= 0; i--) {
    const idx = Math.floor(value / Math.pow(2, i * 5)) & 0x1f;
    out += ALPHABET[idx];
  }
  return `${out.slice(0, 4)}-${out.slice(4)}`;
};

/**
 * Decode and validate a cycle code. Returns `null` if the code is malformed
 * or fails the checksum.
 */
export const decodeCycleCode = (raw: string): CycleCodePayload | null => {
  const cleaned = raw
    .toUpperCase()
    .replace(/[^0-9A-Z]/g, '')
    .replace(/I/g, '1')
    .replace(/L/g, '1')
    .replace(/O/g, '0')
    .replace(/U/g, 'V');
  if (cleaned.length !== 8) return null;
  let value = 0;
  for (const ch of cleaned) {
    const idx = ALPHABET.indexOf(ch);
    if (idx < 0) return null;
    value = value * 32 + idx;
  }
  const crc = value % 0x10000;
  const payload24 = Math.floor(value / 0x10000);
  const bytes = [
    (payload24 >> 16) & 0xff,
    (payload24 >> 8) & 0xff,
    payload24 & 0xff,
  ];
  if (crc16(bytes) !== crc) return null;
  const days = (payload24 >> 10) & 0x3fff;
  const cycleLength = ((payload24 >> 4) & 0x3f) + 18;
  const periodLength = (payload24 & 0x0f) + 1;
  return {
    startDate: epochDayToIso(days),
    cycleLength,
    periodLength,
  };
};
